ALTER TABLE `t_plan` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_task` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_user` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;
